Repository risen228/nextjs-effector, pull requests merged in 2023-04, with the labels that each got.

#34 Feat use official binds
  .babelrc
  README.md
  jest.config.cjs
  library/enhanced-events.ts
  library/with-effector.tsx
  next.config.cjs
  package.json
  postcss.config.cjs
  rollup.config.js
  tailwind.config.сjs
  yarn.lock
Labels: feature

#40 [Documentation] Some proofreading
  .github/workflows/pr-labeler.yml
  .gitignore
  README.md
Labels: documentation

#41 [Feature] Optional props in customize
  README.md
  apps/test-app/.eslintrc.js
  apps/test-app/.eslintrc.json
  apps/test-app/.prettierrc
  apps/test-app/package.json
  apps/test-app/pages/blog/[slug].tsx
  apps/test-app/pages/blog/index.tsx
  apps/test-app/src/pages/blog-post/page.tsx
  apps/test-app/src/pages/blog/page.tsx
  apps/test-app/src/pages/home/page.tsx
  apps/test-app/src/pages/my-profile/page.tsx
  apps/test-app/src/widgets/header/index.tsx
  apps/test-app/yarn.lock
  package.json
  src/enhanced-events.ts
  src/fabrics/get-initial-props.ts
  src/fabrics/get-server-side-props.ts
  src/fabrics/get-static-props.ts
  yarn.lock
Labels: feature

#42 [Chore] Remove test-and-build on push to main branch
  .github/workflows/test-and-build.yml
Labels: chore

#43 [Documentation] Update test app
  README.md
  apps/test-app/.eslintrc.js
  apps/test-app/README.md
  apps/test-app/pages/_app.tsx
  apps/test-app/pages/blog/[slug].tsx
  apps/test-app/pages/blog/index.tsx
  apps/test-app/pages/index.tsx
  apps/test-app/pages/profile/index.tsx
  apps/test-app/src/layouts/factories.ts
  apps/test-app/src/pages/shared/index.ts
  apps/test-app/src/pages/shared/model.ts
  apps/test-app/src/processes/auth.ts
  apps/test-app/src/processes/index.ts
  apps/test-app/src/shared/events/index.ts
  package.json
  yarn.lock
Labels: documentation

#44 Make cjs-compatible import
  src/enhanced-events.ts
Labels: fix
